---

git_repo: https://github.com/akornor/playlistor.git

# Set this flag to true so you can checkout code from a private git repository
# which is setup with an SSH key.
ssh_forward_agent: false

project_name: playlistor
application_name: playlistor

# Note that this PPA doesn't guarantee timely updates in case of security issues.
# Simply remove these two vars below if you prefer to use the official PPA and
# default Python version that came with your Linux distro.
#
# More info here: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
enable_deadsnakes_ppa: true
virtualenv_python_version: python3.7